### ISSUE TITLE
The SECRET_KEY setting must not be empty.

### ISSUE THREAD

**Issue by pjakobsen** [dgrant/django_recipes#2]
When following the instructions in README, I get the following error when I run Step 8: "Run ./manage.py syncdb from the menu".  Here is the full stack trace:

`(django_recipes) laver:django_recipes peder$ ./manage.py syncdb
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/peder/.virtualenvs/django_recipes/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/Users/peder/.virtualenvs/django_recipes/lib/python2.7/site-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/peder/.virtualenvs/django_recipes/lib/python2.7/site-packages/django/core/management/__init__.py", line 190, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "/Users/peder/.virtualenvs/django_recipes/lib/python2.7/site-packages/django/core/management/__init__.py", line 40, in load_command_class
    module = import_module('%s.management.commands.%s' % (app_name, name))
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/peder/.virtualenvs/django_recipes/lib/python2.7/site-packages/django/core/management/commands/syncdb.py", line 4, in <module>
    from django.contrib.auth import get_user_model
  File "/Users/peder/.virtualenvs/django_recipes/lib/python2.7/site-packages/django/contrib/auth/__init__.py", line 7, in <module>
    from django.middleware.csrf import rotate_token
  File "/Users/peder/.virtualenvs/django_recipes/lib/python2.7/site-packages/django/middleware/csrf.py", line 14, in <module>
    from django.utils.cache import patch_vary_headers
  File "/Users/peder/.virtualenvs/django_recipes/lib/python2.7/site-packages/django/utils/cache.py", line 26, in <module>
    from django.core.cache import caches
  File "/Users/peder/.virtualenvs/django_recipes/lib/python2.7/site-packages/django/core/cache/__init__.py", line 34, in <module>
    if DEFAULT_CACHE_ALIAS not in settings.CACHES:
  File "/Users/peder/.virtualenvs/django_recipes/lib/python2.7/site-packages/django/conf/__init__.py", line 48, in __getattr__
    self._setup(name)
  File "/Users/peder/.virtualenvs/django_recipes/lib/python2.7/site-packages/django/conf/__init__.py", line 44, in _setup
    self._wrapped = Settings(settings_module)
  File "/Users/peder/.virtualenvs/django_recipes/lib/python2.7/site-packages/django/conf/__init__.py", line 113, in __init__
    raise ImproperlyConfigured("The SECRET_KEY setting must not be empty.")
django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must not be empty.`

**Comment by pjakobsen** [comment]
I added the following to local.py, still have the same issue:

`SECRET_KEY = '8lu*6g0lg)9z!ba+a$ehk)xt)x%rxgb$i1&amp;022shmi1jcgihb*'`
